### PR TITLE
Add 'error' state

### PR DESCRIPTION
**Pull request by Janrain-Colin**

### CODE REVIEW

**Comment by ticosax** [comment]
Hi @Janrain-Colin ,
I have difficulty to understand the motivation behind this changeset, can you tell us your use case ?

**Comment by Janrain-Colin** [comment]
Part of the design philosophy of this module is that the dictionary elements are immutable once evaluated.  It seems to me, then, that an element that raises an exception when evaluated should raise that exception again each time it is accessed.

**Comment by ticosax** [comment]
@Janrain-Colin I see now, make sense. That something I'd expect also.
While I can merge into my fork, I didn't decided yet to fork the project.

I ping the collaborators on the subject, let's see.

**Comment by Janrain-Colin** [comment]
I'm the original author of this library, and I work with Cameron, so I feel okay with approving this change.

**Comment by ticosax** [comment]
please submit you PR against janrain/lazydict because it needs to be rebased.

**Comment by Janrain-Colin** [comment]
I have rebased this PR on your changes.

**Comment by ticosax** [comment]
Thanks a lot.

**Pull request merged**
